### ISSUE TITLE
Bulletpointing broken in reader view

### ISSUE THREAD

**Issue by SerosKanjus** [hungsu/typomagical-obsidian#52] opened 2022-11-01 12:37 UTC
There are a significant issues with displaying bullet points in reader view, at least in ficus ruby dark mode. 

For a start, in editor view, a bulletpoint, followed by a new line with unbulletpointed text displays as you'd expect it to:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/102552774/199233143-ebbdd376-4c1d-406e-8a73-eb36543bb401.png">

in reader view, however, all the text gets pulled into one block, ruining the point of bullet-pointing and readability in general.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/102552774/199233256-6beeba79-c1cc-4e60-9779-d4150d6d49a7.png">

As you'll notice, for some reason there are also massive gaps between the bulletpoints.
Second level bulletpoints also aren't displaying: from
<img width="388" alt="image" src="https://user-images.githubusercontent.com/102552774/199233478-2b1d3bbd-0ab4-45f9-9ae7-e808484d2cf8.png">
to
<img width="296" alt="image" src="https://user-images.githubusercontent.com/102552774/199233504-01ec91b2-6802-4120-b027-63cad535baea.png">

In other places, however, it's working mostly fine:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/102552774/199233714-5b0b43dd-9233-4c3b-bc54-4f556059845c.png">
to
<img width="734" alt="image" src="https://user-images.githubusercontent.com/102552774/199233752-3e2da764-5836-4148-aeb1-ca5bdbef3d90.png">
though still with the big gap 

I think this may have come with v1.0, but I've put it separately from my other issue on that

**Comment by hungsu** [comment] 2022-11-01 18:01
Hi @SerosKanjus , thanks for your interest in Typomagical!

I had a quick look and it appears that all of these concerns are to do with Obsidian 1.0, not Typomagical or any CSS theme. The HTML generated by Obsidian when I tried to reproduce your bug seems to be nonsense. In editor view as you noted Obsidian correctly registers the bullet as a list, with class `HyperMD-list-line HyperMD-list-line-2`. This should be converted to a new `<li>` in reader mode, but it is not - it's just text inside the existing `<li>`You'll notice that reverting to default theme, or any other theme, results in the same mess.

I'll be closing this issue as it's out of Typomagical's hands, but I strongly encourage you to file something with the official Obsidian board https://forum.obsidian.md/c/bug-reports/7

**Closed by hungsu** 2022-11-01 18:01 UTC
